internal/model/user.go
As discussed, still use old salt at present.
https://t.me/OpenListTeam/13189
=> revert: using old salt value

.github/workflows/beta_release.yml, build.sh
Reference:
https://github.com/OpenListTeam/OpenList/pull/3#pullrequestreview-2921194381
=> chore(ci): using `latest` musl-compilers

cmd/server.go, server/middlewares/error_log.go
add a error logging middleware to log error message to file.
=> feat(log): add error logging middleware for improved error handling

README.md, README_cn.md, README_ja.md, docker-compose.yml
- version is deprecated in docker
- add telegram channel
- add and reorder docs site
=> docs: add Channel and update compose config

docker-compose.yml
=> fix: typo and outdated - compose yaml

drivers/dropbox/meta.go, drivers/dropbox/util.go
=> add dropbox api

drivers/quark_open/driver.go, drivers/quark_open/meta.go, drivers/quark_open/types.go, drivers/quark_open/util.go
为 `夸克网盘Open` 驱动 增加了 `秒传` 和 `缩略图` 功能
修复 令牌刷新判断
=> feat(quark_open): support rapid upload and thumbnail

internal/op/fs.go
fix: https://github.com/OpenListTeam/OpenList/issues/476
=> fix(fs): update objs cache

drivers/strm/driver.go, drivers/strm/util.go
支持多网盘驱动，非alias方式添加路径，查找资源按网盘查找，复制到本地硬盘也直观。
```
支持方式    alias方式
/网盘1      hb:/网盘1
/网盘2      hb:/网盘2
```
=> feat(strm):Support multiple drivers

drivers/115_open/meta.go
=> fix(115open):fix limit_rate save

internal/bootstrap/data/setting.go, internal/model/setting.go
Fixed the verification code OCR recognition service used by multiple drivers. If you need to build your own, please refer to the document: English: https://docs.oplist.org/config/global.html#ocr-api , Chinese: https://docs.oplist.org/zh/config/global.html#ocr-api
=> fix(ocr):Repair verification code OCR recognition service

drivers/115_open/driver.go, go.mod, go.sum, internal/conf/const.go, internal/offline_download/115_open/client.go, internal/offline_download/all.go, internal/offline_download/tool/add.go, internal/offline_download/tool/download.go, server/handles/offline_download.go, server/router.go
添加115open离线下载
相关pr
前端 https://github.com/OpenListTeam/OpenList-Frontend/pull/96
115open sdk https://github.com/OpenListTeam/115-sdk-go/pull/1 (考虑sdk代码直接集成到OpenList里?)
=> feat(115_open): add offline download

internal/bootstrap/data/setting.go, internal/op/setting.go, server/common/proxy.go, server/handles/setting.go, server/router.go
* 前端部分 OpenListTeam/OpenList-Frontend#100
=> feat: default settings api

internal/offline_download/http/client.go
=> fix(simplehttp): logic bug when unable to parse file name

drivers/lenovonas_share/driver.go, drivers/lenovonas_share/meta.go
+ 添加选项：直接显示根文件夹内的文件而不显示根文件夹
+ 从分享链接中提取 shareId
eg. https://siot-share.lenovo.com.cn/s/#/eb.3N93ZbJsaAjerjdm4N
=> feat(lenovonas_share): add option to not show root directory

drivers/terabox/driver.go, drivers/terabox/util.go
1.修复文件上传概率失败问题
2.修订默认UA，避免jstoken刷新失败，see(https://github.com/rclone/rclone/pull/8508)
=> fix(terabox): file upload error

internal/bootstrap/log.go
=> refactor(log): redir utils.Log to logrus after init

pkg/utils/path.go, server/handles/fsbatch.go, server/handles/fsmanage.go
filename清理后变成/filename
close https://github.com/OpenListTeam/OpenList/issues/821
=> fix(fs): rename bug 

internal/conf/const.go, server/static/config.go, server/static/static.go
Close: https://github.com/OpenListTeam/OpenList/issues/754
=> fix(static): support logo replacement

drivers/cloudreve/meta.go, drivers/ilanzou/meta.go
Close: https://github.com/OpenListTeam/OpenList/issues/839
Close: https://github.com/OpenListTeam/OpenList/pull/580
=> feat(drivers): enable local sorting for Cloudreve, ILanZou, and FeijiPan drivers

server/handles/helper.go
identifier有注入风险。
poc:
`/i/LyU0MCUzQ3glM0FzY3JpcHQlMjB4bWxucyUzQXglM0QlMjJodHRwJTNBJTJGJTJGd3d3LnczLm9yZyUyRjE5OTklMkZ4aHRtbCUyMiUzRWFsZXJ0KDEpJTNDJTJGeCUzQXNjcmlwdCUzRQ==`
=> fix(security): potential XSS vulnerabilities

internal/op/fs.go
=> fix(fs): forget cache when get link error

internal/op/fs.go, pkg/singleflight/singleflight.go
=> fix(fs): deadlock when get link error

internal/op/archive.go, internal/op/fs.go
https://go.dev/doc/faq#nil_error
=> fix(fs): nil interface not equal to nil

drivers/123_open/driver.go, drivers/123_open/types.go
1. 将上传方法改为 `driver.PutResult` 类型，更新文件的 fileId 到缓存
2. 固定时区为 UTC+8，修复时间解析错误
Close: https://github.com/OpenListTeam/OpenList/issues/1002
=> feat(123_open): update Put method to return model.Obj

entrypoint.sh
Error: Current user does not have write permissions in the current directory: $(pwd)
Please visit https://doc.oplist.org/guide/installation/docker#for-version-after-v4-1-0 for more information.
错误：当前用户在当前目录没有写权限。
请访问 https://doc.oplist.org/guide/installation/docker#v4-1-0-%E4%BB%A5%E5%90%8E%E7%89%88%E6%9C%AC 获取更多信息。
Exiting...
=> refactor(ci): add permissions check at docker's entrypoint

drivers/quark_uc/util.go, drivers/quark_uc_tv/util.go
The first video info may not contain url.
=> fix(quark): fix getTranscodingLink

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
规范 PR 提交信息
Relates to #376 #352
- https://github.com/OpenListTeam/OpenList-Frontend/pull/148
=> docs(contributing): update guidelines

drivers/wopan/util.go
对 util.go 文件中的 `getTime` 函数进行了修正，将时间解析方式从默认 UTC 改为固定东八区（UTC+8），确保解析出的时间符合中国大陆实际需求。
Closes #1165
=> fix(wopan): use fixed timezone for parsing time

drivers/123/types.go, drivers/123_share/types.go
增加从`123`和`123_share`两个驱动获取到的文件的哈希信息。
Closes #1275
=> fix(123): add get and list hash info

.github/workflows/beta_release.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/release_docker.yml, .github/workflows/test_docker.yml, build.sh
fixes #1286
Closes #XXXX
Relates to #XXXX
=> chore(build): update Go version to 1.25.0 across workflows and build scripts

internal/bootstrap/data/setting.go
=> chore(announcement): change default announcement text

drivers/ilanzou/driver.go
修复蓝奏云优享版的总空间显示错误，原 issue 剩余空间错误的问题已于 #1407 修复。
Closes #1420
未测试
=> fix(ilanzou): wrong total capacity
