drivers/alias/driver.go
drivers/alias/meta.go
drivers/alias/util.go

别名存储增加一个“并行写入”选项，开启时允许向所有冲突路径转发写入操作，类似RAID 1。
与“同名保护”的关系：
| | 开启并行写入 | 关闭并行写入 |
| - | -- | -- |
| 开启同名保护 | 如果所有代理驱动都包含冲突路径，则允许写入，否则不允许写入 | 不允许写入冲突路径 |
| 关闭同名保护 | 向所有包含冲突路径的驱动转发写入操作，不包含冲突路径的驱动无影响 | 只向包含冲突路径的第一个驱动发送写入操作 |
Close AlistGo/alist#8297

feat(alias): support parallel write

---

drivers/189pc/utils.go
drivers/baidu_netdisk/driver.go
drivers/baidu_photo/driver.go
drivers/mopan/driver.go
internal/driver/driver.go

This PR will fix this panic:
```
panic: semaphore: released more than held
goroutine 46665 [running]:
golang.org/x/sync/semaphore.(*Weighted).Release(0xc000598550, 0xc0018a6000?)
/home/runner/go/pkg/mod/golang.org/x/sync@v0.12.0/semaphore/semaphore.go:127 +0xb8
github.com/alist-org/alist/v3/drivers/189pc.(*Cloud189PC).StreamUpload.func2({0x3f39ae8, 0xc0005984b0})
/home/runner/work/alist/alist/drivers/189pc/utils.go:547 +0x418
```
Which is caused by extra semaphore release.

fix(189pc): crashes when upload cancelled

---

drivers/123_open/upload.go
drivers/189pc/utils.go
drivers/baidu_netdisk/driver.go
drivers/baidu_photo/driver.go
drivers/mopan/driver.go

恢复 #79 的改动，这主要是因为`limit`的初始值可以通过
https://github.com/OpenListTeam/OpenList/blob/fc8b99c8623b830037ae5b774afacea3b9da09b6/drivers/189pc/utils.go#L503
的参数`uploadThread`设置，并不需要手动调用`SetLimit`。
感谢 @ljcbaby 指出这一问题。

fix(upload): revert #79

---

README_cn.md

- 将中文 README 文档中的链接格式从改为列表
使中文 README 文档中的链接格式与英文和日文的 README 文档保持一致：
1. 英文版本 ([README.md](https://github.com/OpenListTeam/OpenList/blob/main/README.md)) 
2. 日文版本 ([README_ja.md](https://github.com/OpenListTeam/OpenList/blob/main/README_ja.md))

docs(README_cn): format document links as list to sync with other languages.

---

internal/bootstrap/data/setting.go

- Change PDF.js viewer URL from protocol-relative to HTTPS and updates parameter from "url" to "file" for proper document loading
- Also standardize EPUB.js viewer to use HTTPS protocol for consistency

fix(setting): update PDF and EPUB viewer URLs

---

drivers/cloudreve_v4/util.go

A 404 error message occurs when uploading an S3 storage policy to Cloudreve V4. Files are deleted immediately after they are uploaded to S3, resulting in failed uploads.
According to the request on the browser side, the callback for the S3 storage policy should be a GET request. And the callback for the OneDrive storage policy is a POST request. 
So the callback for S3 should be GET, and the callback for OneDrive should be POST. Both are currently POST, so this PR needs to change S3 to GET.

fix(cloudreve_v4): change upS3 callback method from POST to GET

---

drivers/cloudreve_v4/driver.go

Early Cloudreve V4 used the `/file/create` interface for renaming. It has now been changed to `/file/rename`, causing issues with OpenList renaming. Since overwrite upload requires the use of renaming, it also fails.

fix(cloudreve_v4): update rename api path to `/file/rename`

---

drivers/cloudreve_v4/util.go

The previous code had a problem that would cause it to skip the refresh token step and make direct requests when the access token is empty or invalid, resulting in a CC attack against the target server.

fix(cloudreve_v4): reference error in the refreshToken method

---

drivers/all.go
drivers/quark_open/driver.go
drivers/quark_open/meta.go
drivers/quark_open/types.go
drivers/quark_open/util.go

添加了 `夸克网盘Open` 驱动，采用了官方OpenAPI
---
注意⚠️
- **因缺少官方文档支持，目前只能使用在线API进行令牌刷新操作** -- 相关PR https://github.com/OpenListTeam/cf-worker-api/pull/29
- 上传的秒传部分暂未实现
- 本地令牌刷新未实现
---
驱动添加方式：请完整填入图中的四个字段到`OpenList`对应的驱动添加页面

feat(quark_open): add quark open driver support

---

drivers/thunder/driver.go
drivers/thunder_browser/driver.go
drivers/thunder_browser/meta.go
drivers/thunder_browser/types.go
drivers/thunder_browser/util.go
internal/conf/const.go
internal/offline_download/all.go
internal/offline_download/thunder_browser/thunder_browser.go
internal/offline_download/thunder_browser/util.go
internal/offline_download/tool/add.go
internal/offline_download/tool/download.go
server/handles/offline_download.go
server/router.go

- 修复 `DeviceID` 自动生成相关的BUG
- 修改了 **登录接口** ，使用方法与 `迅雷云盘驱动`  一致
- 跟随官方，更新了相关参数
- 根目录现在将展示为 `迅雷云盘` 根目录：因为官方已经将迅雷浏览器中的数据合并进入迅雷云盘中
- 增加了 `使用流畅播(Use fluent play)` 开关，开启后将使用 `流畅播` 接口进行离线下载，否则将使用 `云添加` 接口进行离线
- 额外说明
- `流畅播`：无法指定目录，文件都将保存到名为`流畅播` 的文件夹中
- |        | 迅雷浏览器会员 | 普通用户 |
| ------ | -------------- | -------- |
| 流畅播 | 无限量         | 每天三次 |
| 云添加 | 每天 500 次    | 三次     |
- 切换开关后，请重新设置 `迅雷浏览器 离线下载目录`
- 后台 ==> 设置 ==> 其他
- 增加了对 **离线下载** 的支持

feat(thunder&thunder_browser): fix deviceId generation & support offline download and update login interface

---

drivers/189pc/utils.go

尝试修复 `天翼云盘客户端` 驱动登录模块中 `getSessionForPC.action` 接口的 `redirectURL` 传参格式错误

fix(189pc): fix redirect_url format

---

drivers/189_tv/driver.go
drivers/189_tv/help.go
drivers/189_tv/meta.go
drivers/189_tv/types.go
drivers/189_tv/utils.go
drivers/all.go

- 相比于之前的 `天翼云盘` 驱动 和 `天翼云盘客户端` 驱动
-  驱动添加 更为便捷，可选 `扫码` 或 `网页短信登录`
- 接口限制，只有旧的上传方式可用，具体限制参考：https://docs.openlist.team/zh/guide/drivers/189.html#%E5%AE%B6%E5%BA%AD%E8%BD%AC%E7%A7%BB
- 暂未实现 `SessionKey` 刷新接口，暂无令牌刷新
---
- 初次添加时，无需填写下面的任何选项
- ![image](https://github.com/user-attachments/assets/0325251b-f330-4658-a5bb-2d33c78a08ee)
- 点击 `保存` 后，右上角会弹出提示
- ![image](https://github.com/user-attachments/assets/547a36df-7a7a-4235-8005-7273a0a92594)
- 此时，返回 存储页面，如下图所示，出现 `登录二维码` 和 `登录链接`
- ![image](https://github.com/user-attachments/assets/c210e96a-4f54-4560-a27e-b359401cbe49)
- 此时可以使用下面的两种方式进行登录
- 使用 `官方客户端` 扫码，确认登录后，**禁用再启用该驱动**，此时应该正常挂载，可进入驱动设置页面进行设置
- 点击 `登录链接`，会打开官方登录页面，选择 短信登录
-  ![image](https://github.com/user-attachments/assets/6e609ffd-755c-4a04-922a-83a7fc389806)
- …

feat(189tv): add 189cloudTV driver

---

drivers/115/driver.go
drivers/115_open/driver.go

获取文件sha1错误导致一些驱动文件复制到115_open时失败

fix(115): error getting file sha1 when upload

---

drivers/quark_uc/driver.go
drivers/quark_uc/meta.go
drivers/quark_uc/types.go
drivers/quark_uc/util.go

- 为 `夸克`驱动，添加 `视频转码地址` 获取的接口
- 文件列表 支持 **只展示视频文件**
- `夸克` 驱动 开放 `302重定向` 选项
---
---
- 注意 开启后 **获取的是转码后的视频文件**，**其文件大小与原视频文件大小不相同**
- 建议搭配
- - `Web proxy` 选项关闭
- - `WebDAV policy`: 使用 `302 redirect` 选项
- - `OnlyListVideoFile` 选项开启

feat(quark): add transcoding link api

---

drivers/all.go
drivers/strm/driver.go
drivers/strm/meta.go
drivers/strm/types.go
drivers/strm/util.go
internal/bootstrap/data/setting.go

添加strm驱动，类似别名驱动，将文件变成strm文件进行挂载
see: https://github.com/OpenListTeam/OpenList/pull/106#issuecomment-2978784374

feat(strm_driver): add strm driver

---

internal/fs/copy.go
internal/fs/move.go
internal/offline_download/http/client.go
internal/offline_download/tool/add.go
internal/offline_download/tool/download.go
internal/offline_download/tool/transfer.go

跳过本地落盘的情况下，直接从远程源下载并流式上传到目标存储
* OpenListTeam/OpenList-Frontend#70

feat(offline-download): stream download to upload

---

drivers/quark_uc_tv/driver.go
drivers/quark_uc_tv/meta.go
drivers/quark_uc_tv/types.go
drivers/quark_uc_tv/util.go

为 `夸克TV` 和 `UCTV` 驱动添加了新的选择项，可选择使用`download`或者`streaming`方式下载文件---**只对视频文件生效**
说明：
- `download` 方式**可获取源视频文件**，但**有下列限速规则**
- **当且仅当 `400MB * 线程数 ＞ 文件大小` 时，不限速**
- 播放操作基本都是单线程，因此可认为播放的视频文件大小＞400MB时，**限速**
- `streaming` 方式**仅可获取转码后的视频文件**，无明显限速规则

feat(quark_uc_tv): add streaming link api

---

drivers/alias/driver.go
drivers/crypt/driver.go
drivers/local/driver.go
drivers/quark_uc/util.go
drivers/quark_uc_tv/util.go
internal/fs/copy.go
internal/model/args.go
internal/model/object.go
internal/offline_download/tool/transfer.go
internal/op/fs.go
internal/stream/stream.go
server/common/proxy.go
server/handles/down.go
server/s3/backend.go
server/webdav/prop.go
server/webdav/webdav.go

Chrome browsers were unable to preview thumbnails, reporting an 'ERR_HTTP_2_PROTOCOL_ERROR'. This was caused by an incorrect content-length header in the server's response for thumbnail images. 
This commit corrects the content-length calculation, allowing Chrome and other compliant clients to render thumbnails correctly.
**Fixes #729**

fix(net): ensure accurate content-length in response

---

drivers/cloudreve_v4/types.go
drivers/cloudreve_v4/util.go

Cloudreve (可能是 Pro?）更新了站点登录配置的返回，导致无法判断是否允许密码登录
Close: #622

fix(cloudreve_v4): remove deprecated authn check for login

---

drivers/pikpak/driver.go
drivers/thunderx/driver.go
drivers/thunderx/types.go
drivers/thunderx/util.go
internal/conf/const.go
internal/offline_download/all.go
internal/offline_download/thunderx/thunderx.go
internal/offline_download/thunderx/utils.go
internal/offline_download/tool/add.go
internal/offline_download/tool/download.go
server/handles/offline_download.go
server/router.go

the copy of https://github.com/AlistGo/alist/pull/8491

feat(thunderx,pikpak): add offline download support for ThunderX; add ctx to specific PikPak functions

---

drivers/doubao/types.go
drivers/doubao_share/types.go
drivers/quark_uc/types.go

- In doubao/types.go:
- Change LastUpdateTime from int to int64
- Change UserCreateTime from int to int64
- In doubao_share/types.go:
- Change CreateTime and UpdateTime from int to int64 in ShareInfo and FilePath
- In quark_uc/types.go:
- Change UpdateTime from int to int64 in TranscodingResp
These changes ensure consistent and accurate representation of timestamp data across the project.

fix(drivers): update time-related fields to int64

---

drivers/115_open/driver.go
go.mod
go.sum
internal/driver/driver.go
internal/op/fs.go

115_open 支持通过path获取文件信息 可以避免目录递归获取 加速link的获取
相关pr https://github.com/OpenListTeam/115-sdk-go/pull/2

feat(115_open): Add GetObjInfo to accelerate getting link

---

internal/bootstrap/patch/all.go
internal/bootstrap/patch/v3_all/rename.go

修复以下问题：
```
[31mERRO[0m[2025-07-31 00:08:22] failed get enabled storages: no driver named: AList V3
```
Close: https://github.com/OpenListTeam/OpenList/issues/908
Close: https://github.com/OpenListTeam/OpenList/issues/156
Close: https://github.com/OpenListTeam/OpenList/issues/122
测试日志：
```                     
[33mWARN[0m[2025-07-31 00:12:59] not enable search                            
[33mWARN[0m[2025-07-31 00:12:59] Rename storage [1]/test from Alist V3 to OpenList 
[33mWARN[0m[2025-07-31 00:12:59] RenameAlistV3Driver: updated 1 storages from Alist V3 to OpenList 
[36mINFO[0m[2025-07-31 00:12:59] init offline download tool ThunderBrowser success: ok 
[36mINFO[0m[2025-07-31 00:12:59] init offline download tool ThunderX success: ok 
[33mWARN[0m[2025-07-31 00:12:59] init …
```

feat(patch): add migration from Alist V3 driver to OpenList

---

cmd/admin.go
cmd/cancel2FA.go
cmd/server.go
cmd/storage.go
internal/bootstrap/data/user.go

#816 #833 引入了 #833 这个问题，虽然  #833 将首次启动时的密码输出到了终端，但还是会输出到日志文件，另外也没有处理 `openlist admin random` 的输出。
---
个人认为，将密码直接写入**日志文件**为比较高危的操作，应当仅通过标准输出输出到控制台中。如果后面有需求将日志输出到前端的设置页面（或者是用户的管理工具支持此操作），然后又使用 HTTP 协议可以中间人监听，这样密码等隐私信息就存在泄露风险。
另外，发现存在一个 `storage` 的运行参数，可以不启动服务直接查看挂载列表，也就是说 OpenList **存在两套 UI**——WebUI 和 TUI（虽然很少见）。之前可能是图方便，CLI 直接用的 logrus 输出，所以 #816 #833 重构日志过滤之后好多东西就打印不出来了。因此应当正确区分处理 CLI 和服务的输出，最好是分开处理。
（图为修复后截取，修复前无 `Found 2 storages`）
---
本 PR 对于基于 `cobra` 的 CLI 部分即 `cmd/**/*.go` 改用 fmt.Print 输出，然后在日志文件中仅记录“从CLI执行了XX操作”的信息，这样就不会将密码等隐私信息直接写入日志文件，同时管理员也可以从日志中审计操作。
对于错误信息，如 `logrus` 的 Error、Fatal，会同时输出到日志和终端，可以暂不调整。

fix(cmd): output to console

---

drivers/strm/driver.go
drivers/strm/meta.go
drivers/strm/types.go
drivers/strm/util.go

Allow user set some file types that need to shown with strm, usually subtitles
Now I have implemented the function of displaying custom files, but I don't understand which function is responsible for managing the actual return file links, please let me know and I will update and commit it
允许在生成Strm的同时下载一些文件，通常为字幕
现在我已经实现了显示文件，但是还没有搞明白负责实际返回文件链接的是哪一个部分，drivers的模板中似乎没有提及。烦请告知，我会继续跟进commit，谢谢！

feat(driver_strm): Also shown some files with strm

---

server/webdav/webdav.go

Implement handling of HEAD requests for directories by setting the correct Content-Type and Content-Length headers.

fix(webdav): Handle HEAD requests for directories with appropriate headers

---

server/common/common.go
server/handles/archive.go
server/handles/down.go
server/middlewares/down.go

Close: #1086
Only modify the behavior of `/d/*path`, `/p/*path`, `/ad/*path`, `/ap/*path`, `/ae/*path`. 
**Not affect `/api`.**
The API will always respond with a 200 status code, with the actual status code wrapped in a JSON object, like the previous response.
Some error status responses are still under discussion. Returning a `500` status code for all errors may not be the most optimal approach.

feat(server): add error page and status code

---

drivers/degoo/driver.go
drivers/degoo/meta.go
drivers/degoo/upload.go
drivers/degoo/util.go

Enhanced Degoo Driver Token Management
- Implemented automatic JWT token expiration detection and refresh functionality
- Added persistent refresh token storage to maintain authentication across service restarts
- Integrated comprehensive rate limiting protection (429 Too Many Requests handling)
- Enhanced login flow with automatic fallback from token refresh to full authentication
- Improved API stability and reduced authentication failures
Technical Improvements
Token Lifecycle Management
- JWT payload parsing with base64 decoding for expiration checking
- Proactive token refresh when expiration is within 5-minute threshold
- Persistent token storage using OpenList's driver storage mechanism
- Graceful error handling with automatic retry logic
Bug Fixes
- Fixed undefined variable …

feat(degoo): token improvement

---

drivers/123_open/meta.go

将 Addition 结构体中 DirectLink 字段的类型标注从 "boolean" 改为 "bool"，以保持 Go 语言类型一致性。
https://t.me/OpenListTeam/114048

fix(123open): change DirectLink type from 'boolean' to 'bool'

---

drivers/123_open/driver.go
drivers/123_open/types.go
drivers/123_open/util.go

1. 修改 fileID 的拼写
2. 修复 UserInfoResp 结构体中的类型错误（直接注释无用部分避免后续调整）
3. 优化直链获取时 UID 的读取逻辑，缓存 UID 
修复 failed link: failed get link: fileID格式异常
配置：
获取直链、直链有效期正常

fix(123open): get direct link

---

internal/op/fs.go

在对文件夹重命名后清除原文件夹下的缓存数据。
修复缓存问题，复现步骤如下：
1. 原文件夹名称为 dir
2. 点击文件夹列出文件列表 list
3. 修改文件夹名称为 dir-bak
4. 新建文件夹，名称为 dir
5. 点击name，数据显示为原dir文件夹下的数据
6. 强制刷新，显示正常
1. 原文件夹状态
2. 重命名文件夹并新建相同名称文件夹
3. 进入新建立的文件夹
4. 强制刷新

fix(fs): clear cache after directory rename to ensure consistency

---

go.mod
go.sum
server/ftp.go
server/ftp/afero.go
server/ftp/fsmanage.go
server/ftp/fsread.go
server/ftp/fsup.go
server/ftp/upload_stage.go
server/sftp.go

原生 FTP 协议不支持在上传开始之前提交文件大小，上传过程中，文件会先完整传到服务端，得到大小后再从服务端上传到驱动。
服务端上传到驱动的过程是异步进行的，开始之前会先直接向客户端返回“上传成功”，在服务端传输到驱动的过程中，如果客户端访问刚刚上传的文件，会得到`ObjectNotFound`，一些客户端会因此判断上传失败或进行重传。
我通过在服务端上传过程中，用本地的临时文件响应客户端的请求，使用引用计数的方式来保证无论是服务端上传先结束还是客户端请求先结束，最终临时文件都可以被删除。
Closes #1288
测试了使用 BCompare 和 FreeFileSync 进行同步，FTP 均成功，SFTP 均不成功，SFTP 不成功的原因推测是二者使用了未实现（因为无法实现）的接口，理论上无法修复。

fix(ftp-server): cannot get obj in uploading state inconsistency window

---

README.md
README_cn.md
README_ja.md
README_nl.md
drivers/all.go
drivers/mediafire/driver.go
drivers/mediafire/meta.go
drivers/mediafire/types.go
drivers/mediafire/util.go
internal/stream/util.go

添加MediaFire驱动
cherry-pick from [alist#9319](https://github.com/AlistGo/alist/commit/d0026030cb36782b92feed55903e85ca14ee6ad0) [alist#9321](https://github.com/AlistGo/alist/commit/16cce37947cab989863a2d444a020ef1c3c46f26)
原作者[D@' 3z K!7](https://github.com/Da3zKi7) 经过@ILoveScratch2 修改
添加Mediafire驱动，并修改以适配OpenList
测试，可成功挂在Mediafire

feat(drivers): add MediaFire driver support

---

internal/errs/unwrap.go
internal/net/serve.go

错误的使用errors.Unwrap errors.Unwrap并没有fallback机制

fix(net): unable to pass HttpStatusCode

---

pkg/utils/io.go

无锁线程安全的SyncClosers最终版本
Close方法的竟态从n次优化到最多2次

perf(sync-closers): improve Close method

---

drivers/123/driver.go
drivers/alias/driver.go
drivers/alias/util.go
drivers/aliyundrive/driver.go
drivers/baidu_netdisk/driver.go
drivers/baidu_netdisk/util.go
drivers/cloudreve_v4/driver.go
drivers/google_drive/driver.go
drivers/ilanzou/driver.go
drivers/pikpak/driver.go
drivers/pikpak/types.go
internal/driver/utils.go
internal/errs/errors.go
internal/model/storage.go
internal/op/archive.go
internal/op/fs.go
internal/op/storage.go
server/handles/storage.go

给`pikpak`添加剩余空间显示支持。
重构了`NewDiskUsageFromUsedAndTotal`所在的位置，修复了`alias`的一个小问题。

feat(pikpak): support disk usage
